export const supportedLocales = ["en", "sw"] as const;
export type Locale = (typeof supportedLocales)[number];

const messages = {
  en: {
    language: "Language", english: "English", swahili: "Kiswahili", save: "Save", switch: "Switch", signOut: "Sign out",
    email: "Email", password: "Password", pleaseWait: "Please wait...", signIn: "Sign in", createAccount: "Create account",
    welcomeBack: "Welcome back", signInDescription: "Sign in to manage your mining operations.", newToMantara: "New to Mantara?", alreadyHaveAccount: "Already have an account?",
    createAccountTitle: "Create your account", createAccountDescription: "Start setting up your organization.", authInvalid: "Enter a valid email and a password of at least 12 characters.", authSignInFailed: "Unable to sign in with those details.", authSignUpFailed: "Unable to create your account. Please try again.", authConfirmEmail: "Check your email to confirm your account, then sign in.",
    setupWorkspace: "Set up your workspace", setupDescription: "Create your company and first mine site. You can add more sites later.", organizationName: "Organization name", firstMineSite: "First mine site", countryCode: "Country code", creating: "Creating...", createOrganization: "Create organization", onboardingInvalid: "Enter an organization name and your first mine site.", onboardingFailed: "We could not create the organization. Please try again.",
    miningOps: "Mining intelligence and operations", organization: "Organization", mineSite: "Mine site", switchWorkspace: "Switch workspace", dashboard: "Dashboard", workers: "Workers", attendance: "Attendance", currentMineSite: "Current mine site",
    workspaceReady: "Your secure organization, membership, mine-site, and permission foundation is ready. Operational dashboard data will appear as each module is implemented.", workspaceShell: "Workspace shell in progress", workspaceShellDescription: "Organization and mine-site context are selected securely. Next: Workers and attendance.",
    workforce: "Workforce", workersDescription: "Personnel registered to {site}.", registerWorker: "Register worker", registerWorkerDescription: "Fields marked required are needed to create the personnel record.", fullName: "Full name", employeeNumber: "Employee or contractor number", phoneNumber: "Phone number", jobTitle: "Job title", employmentType: "Employment type", employee: "Employee", contractor: "Contractor", casual: "Casual", startDate: "Start date", emergencyContactName: "Emergency contact name", emergencyContactPhone: "Emergency contact phone", notes: "Notes", registering: "Registering...", workerRegister: "Worker register", activeRecords: "active records", noWorkers: "No workers are registered at this site yet.", noJobTitle: "No job title", workerInvalid: "Enter the worker's full name and check the worker details.", workerNoContext: "Select an active organization and mine site first.", workerNoPermission: "You do not have permission to register workers.", workerDuplicate: "That employee number already exists in this organization.", workerFailed: "Unable to save the worker. Please try again.", workerCreated: "Worker registered.", workerProfile: "Worker profile", workerDetails: "Worker details", employment: "Employment", contact: "Contact", notProvided: "Not provided", attendanceDescription: "Record and review daily attendance for {site}.", markAttendance: "Mark attendance", attendanceDate: "Attendance date", worker: "Worker", attendanceStatus: "Status", present: "Present", absent: "Absent", late: "Late", leave: "Leave", recording: "Saving...", recordAttendance: "Save attendance", noAttendance: "No attendance records for this site yet.", attendanceRecorded: "Attendance recorded.", attendanceInvalid: "Select a worker, valid date, and attendance status.", attendanceNoPermission: "You do not have permission to record attendance.", attendanceWorkerInvalid: "That worker is not active at the selected mine site.", attendanceFailed: "Unable to save attendance. Please try again.",
  },
  sw: {
    language: "Lugha", english: "English", swahili: "Kiswahili", save: "Hifadhi", switch: "Badilisha", signOut: "Ondoka",
    email: "Barua pepe", password: "Nenosiri", pleaseWait: "Tafadhali subiri...", signIn: "Ingia", createAccount: "Fungua akaunti",
    welcomeBack: "Karibu tena", signInDescription: "Ingia ili kusimamia shughuli zako za uchimbaji.", newToMantara: "Mgeni Mantara?", alreadyHaveAccount: "Una akaunti tayari?",
    createAccountTitle: "Fungua akaunti yako", createAccountDescription: "Anza kusanidi shirika lako.", authInvalid: "Weka barua pepe sahihi na nenosiri lenye angalau herufi 12.", authSignInFailed: "Imeshindikana kuingia kwa taarifa hizo.", authSignUpFailed: "Imeshindikana kufungua akaunti. Tafadhali jaribu tena.", authConfirmEmail: "Angalia barua pepe yako kuthibitisha akaunti, kisha ingia.",
    setupWorkspace: "Sanidi eneo lako la kazi", setupDescription: "Unda kampuni yako na eneo lako la kwanza la mgodi. Unaweza kuongeza maeneo mengine baadaye.", organizationName: "Jina la shirika", firstMineSite: "Eneo la kwanza la mgodi", countryCode: "Msimbo wa nchi", creating: "Inaundwa...", createOrganization: "Unda shirika", onboardingInvalid: "Weka jina la shirika na eneo lako la kwanza la mgodi.", onboardingFailed: "Hatujaweza kuunda shirika. Tafadhali jaribu tena.",
    miningOps: "Akili na usimamizi wa shughuli za uchimbaji", organization: "Shirika", mineSite: "Eneo la mgodi", switchWorkspace: "Badilisha eneo la kazi", dashboard: "Dashibodi", workers: "Wafanyakazi", attendance: "Mahudhurio", currentMineSite: "Eneo la sasa la mgodi",
    workspaceReady: "Msingi salama wa shirika, wanachama, maeneo ya mgodi na ruhusa uko tayari. Taarifa za dashibodi zitaonekana kila moduli itakapokamilika.", workspaceShell: "Muundo wa eneo la kazi unaendelea", workspaceShellDescription: "Shirika na eneo la mgodi huchaguliwa kwa usalama. Kinachofuata: wafanyakazi na mahudhurio.",
    workforce: "Wafanyakazi", workersDescription: "Wafanyakazi waliosajiliwa katika {site}.", registerWorker: "Sajili mfanyakazi", registerWorkerDescription: "Sehemu zenye alama ya lazima zinahitajika kuunda kumbukumbu ya mfanyakazi.", fullName: "Jina kamili", employeeNumber: "Namba ya mfanyakazi au mkandarasi", phoneNumber: "Namba ya simu", jobTitle: "Cheo cha kazi", employmentType: "Aina ya ajira", employee: "Mwajiriwa", contractor: "Mkandarasi", casual: "Kibarua", startDate: "Tarehe ya kuanza", emergencyContactName: "Jina la mawasiliano ya dharura", emergencyContactPhone: "Simu ya mawasiliano ya dharura", notes: "Maelezo", registering: "Inasajiliwa...", workerRegister: "Orodha ya wafanyakazi", activeRecords: "kumbukumbu zinazotumika", noWorkers: "Hakuna wafanyakazi waliosajiliwa katika eneo hili bado.", noJobTitle: "Hakuna cheo cha kazi", workerInvalid: "Weka jina kamili la mfanyakazi na uhakikishe taarifa zake.", workerNoContext: "Chagua shirika na eneo la mgodi linalotumika kwanza.", workerNoPermission: "Huna ruhusa ya kusajili wafanyakazi.", workerDuplicate: "Namba hiyo ya mfanyakazi tayari ipo katika shirika hili.", workerFailed: "Imeshindikana kuhifadhi mfanyakazi. Tafadhali jaribu tena.", workerCreated: "Mfanyakazi amesajiliwa.", workerProfile: "Wasifu wa mfanyakazi", workerDetails: "Taarifa za mfanyakazi", employment: "Ajira", contact: "Mawasiliano", notProvided: "Haijatolewa", attendanceDescription: "Andika na kagua mahudhurio ya kila siku kwa {site}.", markAttendance: "Weka mahudhurio", attendanceDate: "Tarehe ya mahudhurio", worker: "Mfanyakazi", attendanceStatus: "Hali", present: "Amehudhuria", absent: "Hayupo", late: "Amechelewa", leave: "Likizo", recording: "Inahifadhiwa...", recordAttendance: "Hifadhi mahudhurio", noAttendance: "Hakuna kumbukumbu za mahudhurio katika eneo hili bado.", attendanceRecorded: "Mahudhurio yamehifadhiwa.", attendanceInvalid: "Chagua mfanyakazi, tarehe sahihi na hali ya mahudhurio.", attendanceNoPermission: "Huna ruhusa ya kurekodi mahudhurio.", attendanceWorkerInvalid: "Mfanyakazi huyo hayuko katika eneo la mgodi lililochaguliwa.", attendanceFailed: "Imeshindikana kuhifadhi mahudhurio. Tafadhali jaribu tena.",
  },
} as const;

export type MessageKey = keyof typeof messages.en;

export function t(locale: Locale, key: MessageKey, values?: Record<string, string>) {
  let message = messages[locale][key] as string;
  for (const [name, value] of Object.entries(values ?? {})) message = message.replaceAll(`{${name}}`, value);
  return message;
}
