"use client";
import { useActionState } from "react";
import { Button } from "@/components/ui/button";
import { ActionFeedback } from "@/components/ui/feedback";
import { fieldClass, selectClass } from "@/components/ui/form";
import { useT } from "@/lib/i18n/client";
import { createAssay, createDrillHole, createSample, type GeologyState } from "./actions";

export function SampleForm({ today }: { today:string }) { const tr=useT(); const [state,action,pending]=useActionState(createSample,{} as GeologyState); return <form action={action} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
  <label className="text-sm font-semibold">{tr("sampleCode")} *<input required name="sampleCode" className={fieldClass}/></label><label className="text-sm font-semibold">{tr("sampleType")}<select name="sampleType" className={selectClass}>{["rock","soil","channel","chip","core","other"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">{tr("collectedOn")}<input required type="date" name="collectedOn" defaultValue={today} className={fieldClass}/></label>
  <label className="text-sm font-semibold">{tr("latitude")}<input required type="number" step="0.000001" min="-90" max="90" name="latitude" className={fieldClass}/></label><label className="text-sm font-semibold">{tr("longitude")}<input required type="number" step="0.000001" min="-180" max="180" name="longitude" className={fieldClass}/></label><label className="text-sm font-semibold">{tr("fMaterial")}<input name="material" className={fieldClass}/></label><div className="lg:col-span-3"><ActionFeedback state={state}/><Button disabled={pending} className="mt-3">{pending?tr("saving"):tr("addSample")}</Button></div>
  </form>; }
export function AssayForm({ samples, today }:{samples:Array<{id:string;sample_code:string}>;today:string}) { const tr=useT(); const [state,action,pending]=useActionState(createAssay,{} as GeologyState); return <form action={action} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
  <label className="text-sm font-semibold">{tr("sample")}<select required name="sampleId" className={selectClass}>{samples.map(s=><option key={s.id} value={s.id}>{s.sample_code}</option>)}</select></label><label className="text-sm font-semibold">{tr("analyte")}<input required name="analyte" defaultValue="Au" className={fieldClass}/></label><label className="text-sm font-semibold">{tr("assayPpm")}<input required type="number" min="0" step="0.000001" name="valuePpm" className={fieldClass}/></label><label className="text-sm font-semibold">{tr("assayMethod")}<input name="method" className={fieldClass}/></label><label className="text-sm font-semibold">{tr("laboratory")}<input name="laboratory" className={fieldClass}/></label><label className="text-sm font-semibold">{tr("testedOn")}<input type="date" name="testedOn" defaultValue={today} className={fieldClass}/></label><div className="lg:col-span-3"><ActionFeedback state={state}/><Button disabled={pending} className="mt-3">{pending?tr("saving"):tr("addAssay")}</Button></div>
  </form>; }
export function DrillHoleForm() { const tr=useT(); const [state,action,pending]=useActionState(createDrillHole,{} as GeologyState); return <form action={action} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
  <label className="text-sm font-semibold">{tr("holeCode")} *<input required name="holeCode" className={fieldClass}/></label><label className="text-sm font-semibold">{tr("latitude")}<input required type="number" step="0.000001" min="-90" max="90" name="latitude" className={fieldClass}/></label><label className="text-sm font-semibold">{tr("longitude")}<input required type="number" step="0.000001" min="-180" max="180" name="longitude" className={fieldClass}/></label><label className="text-sm font-semibold">{tr("azimuth")}<input type="number" min="0" max="360" step="0.01" name="azimuth" className={fieldClass}/></label><label className="text-sm font-semibold">{tr("dip")}<input type="number" min="-90" max="90" step="0.01" name="dip" className={fieldClass}/></label><label className="text-sm font-semibold">{tr("plannedDepth")}<input type="number" min="0" step="0.01" name="plannedDepth" className={fieldClass}/></label><label className="text-sm font-semibold">{tr("fStatus")}<select name="status" className={selectClass}>{["planned","drilling","completed","abandoned"].map(x=><option key={x}>{x}</option>)}</select></label><div className="lg:col-span-3"><ActionFeedback state={state}/><Button disabled={pending} className="mt-3">{pending?tr("saving"):tr("addDrillHole")}</Button></div>
  </form>; }

