"use client";

import { useActionState } from "react";
import { t, type Locale } from "@/lib/i18n/messages";
import { createWorker, type WorkerState } from "./actions";

export function WorkerForm({ locale }: { locale: Locale }) {
  const [state, action, pending] = useActionState(createWorker, {} as WorkerState);
  return <form action={action} className="grid gap-4 rounded-xl border border-border bg-card p-5 shadow-sm md:grid-cols-2"><div className="md:col-span-2"><h2 className="text-lg font-bold">{t(locale, "registerWorker")}</h2><p className="mt-1 text-sm text-muted-foreground">{t(locale, "registerWorkerDescription")}</p></div><label className="text-sm font-semibold">{t(locale, "fullName")} *<input required name="fullName" maxLength={160} className="mt-1 w-full rounded-lg border border-input px-3 py-2" /></label><label className="text-sm font-semibold">{t(locale, "employeeNumber")}<input name="employeeNumber" maxLength={80} className="mt-1 w-full rounded-lg border border-input px-3 py-2" /></label><label className="text-sm font-semibold">{t(locale, "phoneNumber")}<input name="phoneNumber" inputMode="tel" maxLength={40} className="mt-1 w-full rounded-lg border border-input px-3 py-2" /></label><label className="text-sm font-semibold">{t(locale, "jobTitle")}<input name="jobTitle" maxLength={100} className="mt-1 w-full rounded-lg border border-input px-3 py-2" /></label><label className="text-sm font-semibold">{t(locale, "employmentType")} *<select required name="employmentType" defaultValue="employee" className="mt-1 w-full rounded-lg border border-input bg-card px-3 py-2"><option value="employee">{t(locale, "employee")}</option><option value="contractor">{t(locale, "contractor")}</option><option value="casual">{t(locale, "casual")}</option></select></label><label className="text-sm font-semibold">{t(locale, "startDate")}<input name="startDate" type="date" className="mt-1 w-full rounded-lg border border-input px-3 py-2" /></label><label className="text-sm font-semibold">{t(locale, "emergencyContactName")}<input name="emergencyContactName" maxLength={160} className="mt-1 w-full rounded-lg border border-input px-3 py-2" /></label><label className="text-sm font-semibold">{t(locale, "emergencyContactPhone")}<input name="emergencyContactPhone" inputMode="tel" maxLength={40} className="mt-1 w-full rounded-lg border border-input px-3 py-2" /></label><label className="text-sm font-semibold md:col-span-2">{t(locale, "notes")}<textarea name="notes" maxLength={2000} rows={3} className="mt-1 w-full rounded-lg border border-input px-3 py-2" /></label>{state.error && <p role="alert" className="rounded-lg bg-destructive/12 p-3 text-sm text-destructive md:col-span-2">{state.error}</p>}{state.success && <p role="status" className="rounded-lg bg-success/12 p-3 text-sm text-primary md:col-span-2">{state.success}</p>}<div className="md:col-span-2"><button disabled={pending} className="rounded-lg bg-primary px-4 py-3 font-semibold text-white disabled:opacity-60">{pending ? t(locale, "registering") : t(locale, "registerWorker")}</button></div></form>;
}
